/**
 * map-worlds-schema.ts — types + runtime validator for the committed map
 * catalog `scripts/seed-data/map-worlds.json`.
 *
 * The catalog is the SINGLE source of the galaxy map: the redditor's 992
 * worlds + pixel coordinates from
 * `scripts/seed-data/source/Warhammer_map_SSOT.xlsx`, projected onto a
 * 0–1000 grid, matched against the existing `locations.json` rows, plus the
 * hand-curated links / rollups / pins from
 * `scripts/seed-data/source/map-worlds-curation.xlsx`. Per world the catalog
 * carries the works (books + podcast episodes) that reference the linked
 * location, so the map can answer "has at least one work?" and "which?"
 * WITHOUT a DB connection.
 *
 * Generated by `npm run import:map-worlds` — DO NOT hand-edit the catalog;
 * hand curation goes into `map-worlds-curation.xlsx` and the convert is
 * re-run.
 *
 * Mirrors the `faction-starters-schema.ts` pattern: one module owns the file
 * shape, imported by the convert script, its test, and the app.
 */

export const MAP_WORLDS_SCHEMA = "map-worlds-v2" as const;

/**
 * Curated type groups: every one of the 70 Excel
 * "Primary Classification" values maps onto one of 11 groups; `region` is
 * reserved for curation pins of type Region (never an Excel value). Icons /
 * colors / filters hang off `kind`; the raw classification strings
 * stay available for display.
 */
export const MAP_WORLD_KINDS = [
  "imperial",
  "imperial-military",
  "station",
  "fleet",
  "chaos-warp",
  "gate",
  "aeldari",
  "necron",
  "xenos",
  "dead",
  "unclassified",
  "region",
] as const;
export type MapWorldKind = (typeof MAP_WORLD_KINDS)[number];

/** Junction-role vocabulary — books use `work_locations` roles, episodes the
 *  podcast tag roles. Kept verbatim so the catalog agrees with
 *  what `apply:book` / `apply:podcast` write into the DB. */
export type BookWorkRole = "primary" | "secondary" | "mentioned";
export type EpisodeWorkRole = "subject" | "mentioned";

/** One work attached to a world. `slug` is the `works.slug` the site links to
 *  (`/buch/{slug}` for books); episode slugs are the deterministic
 *  `deriveEpisodeSlug(show, guid)` values `apply:podcast` freezes.
 *  `via`: set when the work arrived through a curation ROLLUP —
 *  it names the source `locations.json` id whose works were attached to this
 *  world (e.g. Imperial-Palace books rolled onto Terra carry
 *  `via: "imperial_palace"`), so the app can show provenance. Absent for works
 *  the world carries through its own `locationId`. */
export type MapWorldWork =
  | { type: "book"; slug: string; title: string; role: BookWorkRole; via?: string }
  | {
      type: "podcast_episode";
      slug: string;
      /** Show slug from the podcast registry (`podcast-shows.json`). */
      show: string;
      title: string;
      role: EpisodeWorkRole;
      via?: string;
    };

export interface MapWorld {
  /** Slugified name; repeated names get deterministic ordinal suffixes
   *  (`commorragh`, `commorragh-2`, … in sheet order). */
  id: string;
  /** Verbatim Excel name (duplicate pins share it) / curation pin name. */
  name: string;
  /** Curated type group — see MAP_WORLD_KINDS. */
  kind: MapWorldKind;
  /** Raw Excel "Primary Classification" verbatim (`"Unclassified"` is a
   *  verbatim source value, not a null); curation pins carry their
   *  Klassifikation cell (`"Region"` for region pins). */
  classification: string | null;
  /** Raw Excel "Secondary Classification" verbatim where set (172 rows);
   *  always null for curation pins. Tertiary is deliberately dropped
   *  (4 rows). */
  classification2: string | null;
  /** One of the five Segmenta for Excel worlds; required for curation pins. */
  segmentum: string | null;
  /** 0–1000 grid, aspect-ratio-true (see `grid.transform`), 2 decimals. */
  gx: number;
  gy: number;
  /** Matched `locations.json` row (→ `/welt/{locationId}`), or null. */
  locationId: string | null;
  /** Works referencing the matched location, plus rolled-up works (`via`).
   *  A world with `locationId: null` can only carry `via` works. */
  works: MapWorldWork[];
  /** Provenance: an Excel row or a hand-curated pin. */
  origin: "excel" | "override";
}

export interface MapWorldsGrid {
  /** gx spans the full [0, gxMax]; gy tops out at gyMax (aspect preserved). */
  gxMax: number;
  gyMax: number;
  /** Human-readable projection formula (documented for hand-placement). */
  transform: string;
}

/** Coverage of the derived media edges: one
 *  (location, work) edge counts as placed when the location is linked by at
 *  least one catalog world (match / link / pin) or rolled up onto one. The app
 *  can render "X of Y work edges on the map" straight from here — summing
 *  `worlds[].works` would double-count duplicate pins. */
export interface MapWorldsCoverage {
  placedWorkEdges: number;
  totalWorkEdges: number;
}

export interface MapWorldsFile {
  $schema: typeof MAP_WORLDS_SCHEMA;
  doc: string;
  grid: MapWorldsGrid;
  coverage: MapWorldsCoverage;
  worlds: MapWorld[];
}

// Runtime validation — cheap structural guard for the generated file, so a
// bad merge/hand-edit fails at convert/test time, not at render time.

const BOOK_ROLES: ReadonlySet<string> = new Set(["primary", "secondary", "mentioned"]);
const EPISODE_ROLES: ReadonlySet<string> = new Set(["subject", "mentioned"]);
const KINDS: ReadonlySet<string> = new Set(MAP_WORLD_KINDS);

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v);
}

function validateWork(w: unknown, at: string, errors: string[]): boolean {
  if (!isObject(w)) {
    errors.push(`${at}: work must be an object`);
    return false;
  }
  if (typeof w.slug !== "string" || w.slug === "") errors.push(`${at}.slug must be a non-empty string`);
  if (typeof w.title !== "string" || w.title === "") errors.push(`${at}.title must be a non-empty string`);
  if (w.via !== undefined && (typeof w.via !== "string" || w.via === "")) {
    errors.push(`${at}.via must be a non-empty string when present`);
  }
  if (w.type === "book") {
    if (typeof w.role !== "string" || !BOOK_ROLES.has(w.role)) {
      errors.push(`${at}.role must be one of ${[...BOOK_ROLES].join("|")}`);
    }
  } else if (w.type === "podcast_episode") {
    if (typeof w.show !== "string" || w.show === "") errors.push(`${at}.show must be a non-empty string`);
    if (typeof w.role !== "string" || !EPISODE_ROLES.has(w.role)) {
      errors.push(`${at}.role must be one of ${[...EPISODE_ROLES].join("|")}`);
    }
  } else {
    errors.push(`${at}.type must be "book" | "podcast_episode"`);
  }
  return w.via !== undefined;
}

/** Validate the parsed catalog; returns error strings ([] = valid). */
export function validateMapWorlds(raw: unknown): string[] {
  const errors: string[] = [];
  if (!isObject(raw)) return ["root must be an object"];
  if (raw.$schema !== MAP_WORLDS_SCHEMA) errors.push(`$schema must be "${MAP_WORLDS_SCHEMA}"`);
  if (typeof raw.doc !== "string") errors.push("doc must be a string");
  if (!isObject(raw.grid)) {
    errors.push("grid must be an object");
  } else {
    if (!isFiniteNumber(raw.grid.gxMax)) errors.push("grid.gxMax must be a finite number");
    if (!isFiniteNumber(raw.grid.gyMax)) errors.push("grid.gyMax must be a finite number");
    if (typeof raw.grid.transform !== "string") errors.push("grid.transform must be a string");
  }
  if (!isObject(raw.coverage)) {
    errors.push("coverage must be an object");
  } else {
    if (!isFiniteNumber(raw.coverage.placedWorkEdges)) errors.push("coverage.placedWorkEdges must be a finite number");
    if (!isFiniteNumber(raw.coverage.totalWorkEdges)) errors.push("coverage.totalWorkEdges must be a finite number");
    if (
      isFiniteNumber(raw.coverage.placedWorkEdges) &&
      isFiniteNumber(raw.coverage.totalWorkEdges) &&
      raw.coverage.placedWorkEdges > raw.coverage.totalWorkEdges
    ) {
      errors.push("coverage.placedWorkEdges must be ≤ coverage.totalWorkEdges");
    }
  }
  if (!Array.isArray(raw.worlds)) return [...errors, "worlds must be an array"];

  const seenIds = new Set<string>();
  raw.worlds.forEach((w, i) => {
    const at = `worlds[${i}]`;
    if (!isObject(w)) {
      errors.push(`${at}: must be an object`);
      return;
    }
    if (typeof w.id !== "string" || w.id === "") errors.push(`${at}.id must be a non-empty string`);
    else if (seenIds.has(w.id)) errors.push(`${at}.id "${w.id}" is duplicated`);
    else seenIds.add(w.id);
    if (typeof w.name !== "string" || w.name === "") errors.push(`${at}.name must be a non-empty string`);
    if (typeof w.kind !== "string" || !KINDS.has(w.kind)) {
      errors.push(`${at}.kind must be one of ${MAP_WORLD_KINDS.join("|")}`);
    }
    if (w.classification !== null && typeof w.classification !== "string") {
      errors.push(`${at}.classification must be string|null`);
    }
    if (w.classification2 !== null && typeof w.classification2 !== "string") {
      errors.push(`${at}.classification2 must be string|null`);
    }
    if (w.segmentum !== null && typeof w.segmentum !== "string") errors.push(`${at}.segmentum must be string|null`);
    if (!isFiniteNumber(w.gx)) errors.push(`${at}.gx must be a finite number`);
    if (!isFiniteNumber(w.gy)) errors.push(`${at}.gy must be a finite number`);
    if (w.locationId !== null && (typeof w.locationId !== "string" || w.locationId === "")) {
      errors.push(`${at}.locationId must be a non-empty string|null`);
    }
    if (w.origin !== "excel" && w.origin !== "override") errors.push(`${at}.origin must be "excel"|"override"`);
    if (!Array.isArray(w.works)) {
      errors.push(`${at}.works must be an array`);
    } else {
      w.works.forEach((work, j) => {
        const hasVia = validateWork(work, `${at}.works[${j}]`, errors);
        if (w.locationId === null && !hasVia) {
          errors.push(`${at}.works[${j}]: a world without locationId can only carry rolled-up works (via)`);
        }
      });
    }
  });
  return errors;
}
