/**
 * map-worlds-schema.ts — types + runtime validator for the committed map
 * catalog `scripts/seed-data/map-worlds.json` (Brief 174, P14 Teil A).
 *
 * The catalog is the SINGLE source of the new galaxy map (P14 Teil B = Brief
 * 178): the redditor's 992 worlds + pixel coordinates from
 * `scripts/seed-data/source/Warhammer_map_SSOT.xlsx`, projected onto a
 * 0–1000 grid, matched against the existing `locations.json` rows, and — per
 * matched world — annotated with the works (books + podcast episodes) that
 * reference that location. The map can answer "hat ≥1 Werk?" and "welche?"
 * per world WITHOUT a DB connection.
 *
 * Generated by `npm run import:map-worlds` — DO NOT hand-edit the catalog;
 * hand corrections go into `scripts/seed-data/map-worlds.overrides.json`
 * and the convert step is re-run.
 *
 * Mirrors the `faction-starters-schema.ts` pattern: one module owns the file
 * shape, imported by the convert script, its test, and (Teil B) the app.
 */

export const MAP_WORLDS_SCHEMA = "map-worlds-v1" as const;

/** Junction-role vocabulary — books use `work_locations` roles, episodes the
 *  podcast tag roles (Brief 109 §7). Kept verbatim so the catalog agrees with
 *  what `apply:book` / `apply:podcast` write into the DB. */
export type BookWorkRole = "primary" | "secondary" | "mentioned";
export type EpisodeWorkRole = "subject" | "mentioned";

/** One work attached to a world. `slug` is the `works.slug` the site links to
 *  (`/buch/{slug}` for books); episode slugs are the deterministic
 *  `deriveEpisodeSlug(show, guid)` values `apply:podcast` freezes. */
export type MapWorldWork =
  | { type: "book"; slug: string; title: string; role: BookWorkRole }
  | {
      type: "podcast_episode";
      slug: string;
      /** Show slug from the podcast registry (`podcast-shows.json`). */
      show: string;
      title: string;
      role: EpisodeWorkRole;
    };

/** Rank-preserving classification (Excel columns B–D). `"Unclassified"` is a
 *  verbatim source value, not a null. */
export interface MapWorldClassification {
  primary: string | null;
  secondary: string | null;
  tertiary: string | null;
}

export interface MapWorld {
  /** Slugified name; repeated names get deterministic ordinal suffixes
   *  (`commorragh`, `commorragh-2`, … in sheet order). */
  id: string;
  /** Verbatim Excel name (duplicate pins share it). */
  name: string;
  classification: MapWorldClassification;
  /** One of the five Segmenta for Excel worlds; nullable for hand-added ones. */
  segmentum: string | null;
  /** 0–1000 grid, aspect-ratio-true (see `grid.transform`), 2 decimals. */
  gx: number;
  gy: number;
  /** Matched `locations.json` row (→ `/welt/{locationId}`), or null. */
  locationId: string | null;
  /** Works referencing the matched location — empty when `locationId` is null. */
  works: MapWorldWork[];
  /** Provenance: an Excel row or a hand-added override world. */
  origin: "excel" | "override";
}

export interface MapWorldsGrid {
  /** gx spans the full [0, gxMax]; gy tops out at gyMax (aspect preserved). */
  gxMax: number;
  gyMax: number;
  /** Human-readable projection formula (documented for hand-placement). */
  transform: string;
}

export interface MapWorldsFile {
  $schema: typeof MAP_WORLDS_SCHEMA;
  doc: string;
  grid: MapWorldsGrid;
  worlds: MapWorld[];
}

// =============================================================================
// Runtime validation — cheap structural guard for the generated file, so a
// bad merge/hand-edit fails at convert/test time, not in a Teil B render.
// =============================================================================

const BOOK_ROLES: ReadonlySet<string> = new Set(["primary", "secondary", "mentioned"]);
const EPISODE_ROLES: ReadonlySet<string> = new Set(["subject", "mentioned"]);

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v);
}

function validateWork(w: unknown, at: string, errors: string[]): void {
  if (!isObject(w)) {
    errors.push(`${at}: work must be an object`);
    return;
  }
  if (typeof w.slug !== "string" || w.slug === "") errors.push(`${at}.slug must be a non-empty string`);
  if (typeof w.title !== "string" || w.title === "") errors.push(`${at}.title must be a non-empty string`);
  if (w.type === "book") {
    if (typeof w.role !== "string" || !BOOK_ROLES.has(w.role)) {
      errors.push(`${at}.role must be one of ${[...BOOK_ROLES].join("|")}`);
    }
  } else if (w.type === "podcast_episode") {
    if (typeof w.show !== "string" || w.show === "") errors.push(`${at}.show must be a non-empty string`);
    if (typeof w.role !== "string" || !EPISODE_ROLES.has(w.role)) {
      errors.push(`${at}.role must be one of ${[...EPISODE_ROLES].join("|")}`);
    }
  } else {
    errors.push(`${at}.type must be "book" | "podcast_episode"`);
  }
}

/** Validate the parsed catalog; returns error strings ([] = valid). */
export function validateMapWorlds(raw: unknown): string[] {
  const errors: string[] = [];
  if (!isObject(raw)) return ["root must be an object"];
  if (raw.$schema !== MAP_WORLDS_SCHEMA) errors.push(`$schema must be "${MAP_WORLDS_SCHEMA}"`);
  if (typeof raw.doc !== "string") errors.push("doc must be a string");
  if (!isObject(raw.grid)) {
    errors.push("grid must be an object");
  } else {
    if (!isFiniteNumber(raw.grid.gxMax)) errors.push("grid.gxMax must be a finite number");
    if (!isFiniteNumber(raw.grid.gyMax)) errors.push("grid.gyMax must be a finite number");
    if (typeof raw.grid.transform !== "string") errors.push("grid.transform must be a string");
  }
  if (!Array.isArray(raw.worlds)) return [...errors, "worlds must be an array"];

  const seenIds = new Set<string>();
  raw.worlds.forEach((w, i) => {
    const at = `worlds[${i}]`;
    if (!isObject(w)) {
      errors.push(`${at}: must be an object`);
      return;
    }
    if (typeof w.id !== "string" || w.id === "") errors.push(`${at}.id must be a non-empty string`);
    else if (seenIds.has(w.id)) errors.push(`${at}.id "${w.id}" is duplicated`);
    else seenIds.add(w.id);
    if (typeof w.name !== "string" || w.name === "") errors.push(`${at}.name must be a non-empty string`);
    if (!isObject(w.classification)) {
      errors.push(`${at}.classification must be an object`);
    } else {
      for (const rank of ["primary", "secondary", "tertiary"] as const) {
        const v = w.classification[rank];
        if (v !== null && typeof v !== "string") errors.push(`${at}.classification.${rank} must be string|null`);
      }
    }
    if (w.segmentum !== null && typeof w.segmentum !== "string") errors.push(`${at}.segmentum must be string|null`);
    if (!isFiniteNumber(w.gx)) errors.push(`${at}.gx must be a finite number`);
    if (!isFiniteNumber(w.gy)) errors.push(`${at}.gy must be a finite number`);
    if (w.locationId !== null && (typeof w.locationId !== "string" || w.locationId === "")) {
      errors.push(`${at}.locationId must be a non-empty string|null`);
    }
    if (w.origin !== "excel" && w.origin !== "override") errors.push(`${at}.origin must be "excel"|"override"`);
    if (!Array.isArray(w.works)) {
      errors.push(`${at}.works must be an array`);
    } else {
      if (w.locationId === null && w.works.length > 0) {
        errors.push(`${at}: works must be empty when locationId is null`);
      }
      w.works.forEach((work, j) => validateWork(work, `${at}.works[${j}]`, errors));
    }
  });
  return errors;
}
