/**
 * Atlas-Regen — Postgres → external Obsidian vault.
 *
 * Mechanically generates the chrono-atlas vault (book domain) from
 * Postgres. The Atlas is a read-only mirror; Postgres is canonical.
 *
 * Skeleton (Brief 049): writes INDEX.md plus a single proof-of-render
 * book and faction. Full rendering (all books, all factions, quality
 * views) is a follow-up brief.
 *
 * Usage:
 *   npm run atlas:regen
 *   npm run atlas:regen -- --out=/some/path/chrono-atlas
 *   npm run atlas:regen -- --help
 *
 * Default output path: $HOME/chrono-atlas (e.g. C:\Users\Phil\chrono-atlas
 * on Windows). Override with --out=<path> or env ATLAS_PATH.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";
import { parseArgs } from "node:util";

import { eq, asc } from "drizzle-orm";

import { db } from "@/db/client";
import { works, factions } from "@/db/schema";

interface CliConfig {
  outPath: string;
  help: boolean;
}

function parseCliArgs(argv: string[]): CliConfig {
  const { values } = parseArgs({
    args: argv,
    options: {
      out: { type: "string" },
      help: { type: "boolean", short: "h", default: false },
    },
    strict: true,
    allowPositionals: false,
  });

  const envOverride = process.env.ATLAS_PATH;
  const defaultPath = path.join(homedir(), "chrono-atlas");
  const outPath = values.out ?? envOverride ?? defaultPath;

  return {
    outPath: path.resolve(outPath),
    help: Boolean(values.help),
  };
}

function printHelp(): void {
  const defaultPath = path.join(homedir(), "chrono-atlas");
  console.log(`atlas-regen — Postgres → chrono-atlas Obsidian vault

Usage:
  npm run atlas:regen
  npm run atlas:regen -- --out=<path>
  npm run atlas:regen -- --help

Options:
  --out=<path>    Vault output directory. Default: ${defaultPath}
                  (or env ATLAS_PATH if set).
  -h, --help      Print this message.

The Atlas is generated mechanically from Postgres. Postgres is the
single source of truth; the Atlas mirrors it. Re-running is idempotent
and overwrites existing files. See brain/wiki/workflows/atlas-regen.md
for the workflow context.
`);
}

interface BookRow {
  slug: string;
  title: string;
}

interface FactionRow {
  id: string;
  name: string;
}

async function fetchFirstBook(): Promise<BookRow | null> {
  const rows = await db
    .select({ slug: works.slug, title: works.title })
    .from(works)
    .where(eq(works.kind, "book"))
    .orderBy(asc(works.slug))
    .limit(1);

  return rows[0] ?? null;
}

async function fetchFirstFaction(): Promise<FactionRow | null> {
  const rows = await db
    .select({ id: factions.id, name: factions.name })
    .from(factions)
    .orderBy(asc(factions.id))
    .limit(1);

  return rows[0] ?? null;
}

async function countBooks(): Promise<number> {
  const rows = await db
    .select({ slug: works.slug })
    .from(works)
    .where(eq(works.kind, "book"));
  return rows.length;
}

async function countFactions(): Promise<number> {
  const rows = await db.select({ id: factions.id }).from(factions);
  return rows.length;
}

function renderBookMarkdown(book: BookRow, generatedAt: string): string {
  return `---
slug: ${book.slug}
title: ${JSON.stringify(book.title)}
generated: ${generatedAt}
---

# ${book.title}

> Wikilink anchor: [[books/${book.slug}|${book.title}]]
>
> Generated mechanically from Postgres via \`npm run atlas:regen\`. This is a
> proof-of-render — full per-book detail (synopsis, primary era, factions,
> characters, locations, sources, ratings) lands in a follow-up brief.
> Postgres is canonical; do not edit this file by hand.

## What this page will eventually carry

- Synopsis (LLM-paraphrased, license-safe, 100–150 W)
- Primary era anchor (\`book_details.primary_era_id\`)
- Factions involved (Wikilinks to \`factions/<id>\`)
- Characters (Wikilinks to \`characters/<id>\`)
- Primary locations (Wikilinks to \`locations/<id>\`)
- Source provenance (per-field origins from the multi-source merge)
- Rating + rating source
- External links (read / listen / watch / buy_print)

For the regeneration workflow, see
[chrono-lexicanum/brain/wiki/workflows/atlas-regen.md](https://github.com/phinklab/chrono-lexicanum/blob/main/brain/wiki/workflows/atlas-regen.md).
`;
}

function renderFactionMarkdown(faction: FactionRow, generatedAt: string): string {
  return `---
id: ${faction.id}
name: ${JSON.stringify(faction.name)}
generated: ${generatedAt}
---

# ${faction.name}

> Wikilink anchor: [[factions/${faction.id}|${faction.name}]]
>
> Generated mechanically from Postgres via \`npm run atlas:regen\`. This is a
> proof-of-render — full per-faction detail (alignment, sub-factions,
> tone, books featuring this faction, key characters/locations) lands in
> a follow-up brief.

## What this page will eventually carry

- Alignment (\`imperium | chaos | xenos | neutral\`)
- Sub-factions (self-FK on \`factions.parent_id\`)
- Books featuring this faction (Wikilinks to \`books/<slug>\`)
- Key characters of this faction (Wikilinks to \`characters/<id>\`)
- Notable locations (Wikilinks to \`locations/<id>\`)

For the regeneration workflow, see
[chrono-lexicanum/brain/wiki/workflows/atlas-regen.md](https://github.com/phinklab/chrono-lexicanum/blob/main/brain/wiki/workflows/atlas-regen.md).
`;
}

function renderIndexMarkdown(opts: {
  generatedAt: string;
  outPath: string;
  bookCount: number;
  factionCount: number;
  proofBookSlug: string | null;
  proofFactionId: string | null;
}): string {
  const proofLines: string[] = [];
  if (opts.proofBookSlug) {
    proofLines.push(`- Book proof-of-render: [[books/${opts.proofBookSlug}]]`);
  } else {
    proofLines.push(`- Book proof-of-render: (none — DB has no books with kind='book')`);
  }
  if (opts.proofFactionId) {
    proofLines.push(`- Faction proof-of-render: [[factions/${opts.proofFactionId}]]`);
  } else {
    proofLines.push(`- Faction proof-of-render: (none — DB has no factions)`);
  }

  const dbStatus =
    opts.bookCount === 0 && opts.factionCount === 0
      ? `> ⚠ Postgres returned no books and no factions. The Atlas skeleton has been created
> but holds no entity data. Re-run \`npm run atlas:regen\` after the first 3d-Apply or
> \`npm run db:seed\`.`
      : `> Postgres → Atlas mirroring is one-way. Postgres is canonical.`;

  return `# chrono-atlas — INDEX

> Generated mechanically from Postgres via \`npm run atlas:regen\`.
> Read-only mirror; Postgres is canonical for the W40k novel domain.

**Generated:** ${opts.generatedAt}
**Vault path:** \`${opts.outPath}\`

## Counts

- Books in Postgres (kind='book'): **${opts.bookCount}**
- Factions in Postgres: **${opts.factionCount}**
- Books rendered to this Atlas: ${opts.proofBookSlug ? "1 (proof)" : "0"}
- Factions rendered to this Atlas: ${opts.proofFactionId ? "1 (proof)" : "0"}

${dbStatus}

## Proof-of-render entries (Brief 049 skeleton)

${proofLines.join("\n")}

## Layout

- \`books/\` — per-book Markdown (one file per work where \`kind='book'\`)
- \`factions/\` — per-faction Markdown
- \`INDEX.md\` (this file) — generation timestamp + counts + pointers

## Out-of-scope (today)

- Per-book full rendering (synopsis, era, factions, characters, locations, sources, ratings) — follow-up brief.
- Per-faction full rendering (alignment, sub-factions, books, characters) — follow-up brief.
- Cross-page quality views (Dataview-plugin queries) — Obsidian-side, follow-up.
- Pruning of orphaned files when entities removed from Postgres — follow-up.

## Workflow

See \`chrono-lexicanum/brain/wiki/workflows/atlas-regen.md\` for when to run, configuration, and what to do on DB-vs-Atlas divergence.
`;
}

async function main(): Promise<void> {
  const cli = parseCliArgs(process.argv.slice(2));

  if (cli.help) {
    printHelp();
    process.exit(0);
  }

  const generatedAt = new Date().toISOString();
  const booksDir = path.join(cli.outPath, "books");
  const factionsDir = path.join(cli.outPath, "factions");

  console.log(`[atlas-regen] target vault: ${cli.outPath}`);
  console.log(`[atlas-regen] starting at  ${generatedAt}`);

  await mkdir(cli.outPath, { recursive: true });
  await mkdir(booksDir, { recursive: true });
  await mkdir(factionsDir, { recursive: true });

  let firstBook: BookRow | null = null;
  let firstFaction: FactionRow | null = null;
  let bookCount = 0;
  let factionCount = 0;

  try {
    [firstBook, firstFaction, bookCount, factionCount] = await Promise.all([
      fetchFirstBook(),
      fetchFirstFaction(),
      countBooks(),
      countFactions(),
    ]);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(
      `[atlas-regen] DB query failed: ${message}\n` +
        `Hint: confirm DATABASE_URL is set in .env.local and the pooler endpoint is reachable.`,
    );
    process.exit(1);
  }

  if (firstBook) {
    const bookPath = path.join(booksDir, `${firstBook.slug}.md`);
    await writeFile(bookPath, renderBookMarkdown(firstBook, generatedAt), "utf8");
    console.log(`[atlas-regen] wrote ${path.relative(cli.outPath, bookPath)}`);
  } else {
    console.log(`[atlas-regen] no books in DB — skipping book proof-of-render`);
  }

  if (firstFaction) {
    const factionPath = path.join(factionsDir, `${firstFaction.id}.md`);
    await writeFile(factionPath, renderFactionMarkdown(firstFaction, generatedAt), "utf8");
    console.log(`[atlas-regen] wrote ${path.relative(cli.outPath, factionPath)}`);
  } else {
    console.log(`[atlas-regen] no factions in DB — skipping faction proof-of-render`);
  }

  const indexPath = path.join(cli.outPath, "INDEX.md");
  await writeFile(
    indexPath,
    renderIndexMarkdown({
      generatedAt,
      outPath: cli.outPath,
      bookCount,
      factionCount,
      proofBookSlug: firstBook?.slug ?? null,
      proofFactionId: firstFaction?.id ?? null,
    }),
    "utf8",
  );
  console.log(`[atlas-regen] wrote INDEX.md`);

  console.log(
    `[atlas-regen] done. Books in DB: ${bookCount}, factions in DB: ${factionCount}. ` +
      `Open ${cli.outPath} as an Obsidian vault to inspect.`,
  );

  // Drizzle/postgres-js keeps the connection pool open; close it so the
  // process can exit cleanly.
  process.exit(0);
}

main().catch((err) => {
  const message = err instanceof Error ? err.message : String(err);
  console.error(`[atlas-regen] fatal: ${message}`);
  process.exit(1);
});
